;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        beginning-of-visual-line
        clipboard-kill-ring-save
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        dabbrev-expand
        haskell-indentation-common-electric-command
        haskell-indentation-newline-and-indent
        kill-region
        markdown-enter-key
        my-backward-kill-line
        my-forward-block
        ruby-electric-close-matching-char
        ruby-electric-space
        scroll-down-lot
        scroll-up-lot
        slim-electric-backspace
        string-rectangle
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        end-of-buffer
        end-of-visual-line
        haml-electric-backspace
        haskell-mode-contextual-space
        kill-rectangle
        repeat
        ruby-electric-bar
        tabbar-backward-tab
        tabbar-forward-tab
        ))
