;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        clipboard-kill-ring-save
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        dabbrev-expand
        ruby-electric-close-matching-char
        ruby-electric-space
        slim-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        kill-rectangle
        repeat
        tabbar-backward-tab
        tabbar-forward-tab
        ))
